export const Config = {
   OPENAI_API_KEY: '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'
}